format_version: v1.0
type: UniqueComponent
attributes: {id: uart4}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '216'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '0'}
  - type: Comment
    attributes: {id: UART_BRGH_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** High Speed mode 4x baud clock enabled (BRGH =
            1) ***'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '100000000'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '8'}
- type: ElementPosition
  attributes: {x: '217', y: '47', id: uart4}
